(if #t
    (if (not #f)
        (if (> 10 0)
            (if (>= 5 5)
                (if (eq? 1 1)
                    (if (<= 2 3)
                        (if (< 1 4)
                            (if (and #t #t)
                                (if (or #f #f)
                                    10
                                    9)
                                8)
                            7)
                        6)
                    5)
                4)
            3)
        2)
    1)
